"""
Django settings for patent_ai project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import concurrent.futures
import datetime
import os
import threading
from datetime import timedelta
from pathlib import Path

import pandas as pd

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*ny$4(ms$sm5z4^yc_wts#nc22j$!ot5yj8$d*)k4e#x6_$l5+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'file',
    'analysis',
    'user'
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication'
    ],
    'EXCEPTION_HANDLER': 'patent_ai.exceptions.handle_exceptions',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
AUTH_USER_MODEL = 'user.UserModel'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7)
}
ROOT_URLCONF = 'patent_ai.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'patent_ai.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

KIMI_TIMEOUT = 300

CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_REGEX_WHITELIST = [  # 可跨域白名单设置
    "*",  # 前段请求的IP地址
]
CORS_ALLOW_METHODS = ("*")  # 配置允许的请求方式
CORS_ALLOW_HEADERS = ("*")  # 配置允许的请求头
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie
APPEND_SLASH = False
TEMP_KEY_NAME_LIST = ["版本号", "专利名称", "专利申请号", "申请公布号", "专利类型", "法律状态", "申请人", "发明人",
                      "应用领域所属传统行业", "应用领域所属战略新兴产业", "解决问题",
                      "技术效果", "技术手段", "创新点", "专利描述", "市场现有技术整理与分析",
                      "本发明与现有技术的比较分析",
                      "潜在应用场景", "产业化前景", "最佳应用场景建议", "分析逻辑和理由", "作画问题",
                      "细分市场及策略", "关键业务",
                      "重要伙伴", "核心资源", "价值主张", "客户关系", "渠道通路", "客户细分", "成本结构",
                      "收入来源", "合作企业", "专利保护范围评价", "专利保护范围分数",
                      "专利稳定性评价", "专利稳定性分数", "专利技术先进性评价", "技术先进性分数",
                      "专利技术实施难度评价", "技术实施难度分数", "专利技术社会与经济影响评价",
                      "社会与经济影响分数", "专利市场需求评价", "市场需求分数", "专利潜在商业价值评价",
                      "潜在商业价值分数", "市场推广难度评价", "市场推广难度分数",
                      "综合性评价", "综合评分", "本发明可能面临的挑战及建议", "行业分类"]

PROBLEM_MAPPING_KEY_JSON = {
    "1": {"专利名称", "专利申请号", "申请公布号", "专利类型", "法律状态", "申请人", "发明人", "应用领域所属传统行业",
          "应用领域所属战略新兴产业", "解决问题", "技术效果", "技术手段", "创新点", "专利描述", "技术实施细节"},
    "5": {"本发明与现有技术的比较分析", "市场现有技术整理与分析"},
    "6": {"潜在应用场景"},
    "7": {"产业化前景"},
    "8": {"最佳应用场景建议", "分析逻辑和理由"},
    "9": {"细分市场及策略"},
    "10": {'价值主张', '客户关系', '客户细分', '渠道通路', '重要伙伴', '关键业务', '核心资源', '成本结构', '收入来源'},
    "11": {"合作企业"},
    "13": {'专利保护范围评价', '专利稳定性评价', '专利技术先进性评价', '专利技术实施难度评价',
           '专利技术社会与经济影响评价', '专利市场需求评价', '专利潜在商业价值评价', '市场推广难度评价', '综合性评价'},
    "15": {"本发明可能面临的挑战及建议"},
    "16": {"行业分类"}
}
# 同时并发的控制
semaphore = threading.BoundedSemaphore(1)
lock = threading.Lock()
# 获取当前日期
today = datetime.date.today()

# 生成日志目录路径，例如：logs/2024/06/13/
log_directory = os.path.join('logs', today.strftime('%Y'), today.strftime('%m'), today.strftime('%d'))
# 报告的版本号前缀
VERSION_PREFIX = today.strftime('%Y') + "PD"

# 创建目录
os.makedirs(log_directory, exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message} ({pathname}:{lineno})',
            'style': '{',
        },
        'simple': {
            'format': '{asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filters': ['require_debug_false'],
            'filename': os.path.join(log_directory, 'debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 30,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console', ],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'patent_ai': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
CELERYD_CONCURRENCY = 1
df = pd.read_excel('all.xlsx')
# class_df = pd.read_excel('class.xlsx',sheet_name="sheet1")
class_name_df = pd.read_excel('class.xlsx', sheet_name="Sheet2")

# 阿里云通义万相API配置
# 获取API Key: https://dashscope.console.aliyun.com/
# 请在development.py或production.py中覆盖此配置
DASHSCOPE_API_KEY = "sk-d235a0612a0a4a5da8c17fd44b5e28c7"
